---
#echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: app-jwt
  namespace: default  
plugin: jwt
config:
  secret_is_base64: "true"
#" | kubectl apply -f -

---
#echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: admin
  annotations:
    kubernetes.io/ingress.class: kong
  namespace: default    
username: admin
credentials:
- admin-jwt
#" | kubectl apply -f -

---
#echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user
  annotations:
    kubernetes.io/ingress.class: kong
  namespace: default    
username: user
credentials:
- user-jwt
#" | kubectl apply -f -


